services:
  bot:
    image: vinland_bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6767:6767"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  downloader:
    image: vinland_downloader
    build:
      context: ./bot/services
      dockerfile: dockerfile
    restart: unless-stopped
    # Порт 67 не нужен — воркер общается с базой и редисом внутри docker-сети
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: