"""added download_format column

Revision ID: 1862ae8fc6ba
Revises: 1509af08d980
Create Date: 2026-06-26 01:13:06.482536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1862ae8fc6ba'
down_revision: Union[str, Sequence[str], None] = '1509af08d980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('download_format', sa.String(length=5), server_default=sa.text("'audio'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'download_format')
    # ### end Alembic commands ###
