FROM python:3.13-slim


RUN apt-get update && apt install -y \
    ffmpeg \ 
    curl \ 
    unzip  

RUN curl -fsSL https://deno.land/install.sh | sh

ENV PATH="/root/.deno/bin:${PATH}"


WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt 

COPY . . 

CMD ["python","backend.py"]
